### ISSUE TITLE
Add isBasedOnUrl

### ISSUE THREAD

**Issue by philbarker** [dcmi/lrmi-examples#9]
I've been wondering about how to acknowledge that the alignmentsUK example started life as a description on the BBC Bytesize website. Using https://schema.org/isBasedOnUrl would seem to be a good way of doing this and providing an example for one more LRMI property.

**Comment by stuartasutton** [comment]
Phil, this makes sense to me.

**Comment by jgoodell2** [comment]
I agree. https://schema.org/isBasedOnUrl works.
